### ISSUE TITLE
How to train on the dataset which is sequential?

### ISSUE THREAD

**Issue by manapshymyr-OB** [VSainteuf/pytorch-psetae#21]
Hello! I have a dataset which is sequential. I have a varying length of data, for example for object 109x8x316 or 90x8x517. I have tried to put **order** for positions and **137** for  --lms, while I am getting the following error RuntimeError: stack expects each tensor to be equal size, but got [105, 8, 64] at entry 0 and [109, 8, 64] at entry 1. Can you guide on this please?

**Comment by VSainteuf** [comment]
HI @manapshymyr-OB ,
can you have a look at [this issue](https://github.com/VSainteuf/lightweight-temporal-attention-pytorch/issues/1) and see if it helps you?

**Comment by manapshymyr-OB** [comment]
I have tried that one. but getting this error:
File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1134, in _try_get_data
    data = self._data_queue.get(timeout=timeout)

do you have any idea what can cause the problem?

**Comment by manapshymyr-OB** [comment]
Furthermore, I am wondering how to handle error that is caused by return torch.stack(batch, 0, out=out). it says that dimensions are not same...

**Comment by manapshymyr-OB** [comment]
I executed following your comments and getting this error:
```
Traceback (most recent call last):
  File "/agrospace/lightweight-temporal-attention-pytorch/train.py", line 363, in <module>
    main(config)
  File "/agrospace/lightweight-temporal-attention-pytorch/train.py", line 256, in main
    train_metrics = train_epoch(model, optimizer, criterion, train_loader, device=device, config=config)
  File "/agrospace/lightweight-temporal-attention-pytorch/train.py", line 26, in train_epoch
    for i, (x, y) in enumerate(data_loader):
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 632, in __next__
    data = self._next_data()
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1350, in _next_data
    return self._process_data(data)
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1376, in _process_data
    data.reraise()
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 280, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/agrospace/lightweight-temporal-attention-pytorch/vevn/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 177, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [123, 8, 64] at entry 0 and [117, 8, 64] at entry 1
```

and when I print the batch shapes with the following code:
```
for b in batch:
        print(b.shape)
    return torch.stack(batch, 0, out=out)
```

I see this:
<img width="143" alt="image" src="https://github.com/VSainteuf/pytorch-psetae/assets/61227498/81adf9ba-d97a-497d-b512-2e05db7cc553">
which is correct (the first number represents sequence)
Any ideas how to work correctly with the sequential data (so I do not have equal data in terms of the time)?

**Comment by VSainteuf** [comment]
yes if you have time series of varying length, you need to implement a "collate" function with a padding strategy to form batches of equal size. 
You can have a look at how we did it for the PASTIS dataset [here](https://github.com/VSainteuf/utae-paps/blob/001fcbbada7988e4bd4c1c37bfead2c23d21df4a/src/utils.py)

**Comment by manapshymyr-OB** [comment]
Thanks! Your comments helped out
